version: '3.7'

services:
  php:
    build:
      context: ./docker/fpm
      args:
        PHALCON_VERSION: 5.1.4
        PSR_VERSION: 1.1.0
        PHP_VERSION: 8.1
    restart: unless-stopped
    volumes:
      - ./:/var/www/html

  nginx:
    build: ./docker/nginx
    restart: unless-stopped
    ports:
      - "80:80"

  db:
    image: mysql:8.0.32
#    user: "root"
    environment:
      MYSQL_DATABASE: 'testdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/db:/var/lib/mysql